apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc  # Name of the Persistent Volume Claim
spec:
  accessModes:
    - ReadWriteMany  # Access mode for the PVC, allowing multiple pods to read and write
  resources:
    requests:
      storage: 350Gi  # Requested amount of storage. Should match or be less than the PV capacity
  storageClassName: efs-sc  # Storage class that defines the EFS storage configuration
